### ISSUE TITLE
Project team members with social contact (e.g. linkedIn, twitter)

### ISSUE THREAD

**Issue by eddiejaoude** [HackBrexit/hackbrexit.github.io#12]

**Comment by tanyapowell** [comment]
@eddiejaoude should we set up a typeform or something similar to gather/collate details from people?

**Comment by eddiejaoude** [comment]
@tanyapowell I think one was already done. Well an google spreadsheet & link sent out in the last email.

**Comment by charlottebrf** [comment]
Hey @tanyapowell @eddiejaoude do you need the link to this data? We take attendance at the open source accelerator programme so collecting emails

**Comment by eddiejaoude** [comment]
As the team members have changed quite a bit, I am not sure if this is relevant anymore. It will probably become relevant again but for the moment I don't think it is. @tanyapowell thoughts?

PS. I recommend we close this for now & create a new one when required.

**Comment by tanyapowell** [comment]
Yep! I agree with @eddiejaoude. Let's close this for now and re-open if/when required
