### ISSUE TITLE
Add sign up form

### ISSUE THREAD

**Issue by laurapaterson** [HackBrexit/hackbrexit.github.io#18]
Let's add a mini form to gather emails so we can identify people interested in joining the community.

**Comment by laurapaterson** [comment]
The form should include check boxes if people want to sign up to the CF:G/ TW mailing lists, so that we can import interested parties to other event/recruitment mail shots.

**Comment by eddiejaoude** [comment]
Is there an existing form? (e.g. typeeform or similar), we could just put a link to it for now on the website for now. What do you think?

**Comment by eddiejaoude** [comment]
@charlottebrf ^^

**Comment by charlottebrf** [comment]
@eddiejaoude @laurapaterson Apologies for slowness on this one... I've just written instructions for CF: G curriculum on adding a google form using <iframe> tag to embed it. Might this work? I will also explore the type form option as the UX is much nicer on that one.

**Comment by charlottebrf** [comment]
@eddiejaoude accepting responsibility for this one, will be done by end of week- sorry was busy over the weekend

**Comment by laurapaterson** [comment]
Apologies, just got this - since I went post-tech, github emails skip the
inbox...

Dr C, I have a new dev started today, so if I can hand it off to her, let
me know :)  I'll be back in the office tomorrow.

**Comment by charlottebrf** [comment]
Heya @laurapaterson do you know what... that would be great if the dev could do it. I will add the press links though @eddiejaoude - catching up on Hack Brexit emails today. Maybe I could do our open source accelerator on github instead of a google doc- eh @eddiejaoude ..

**Comment by eddiejaoude** [comment]
> Maybe I could do our open source accelerator on github instead of a google doc- eh

Yay! 👍

**Comment by laurapaterson** [comment]
You know, I only just saw your last comment on this Charlotte - I'm away to set up a redirect for hackbrexit emails!

**Comment by charlottebrf** [comment]
Tasks to be done:

1. [x] Create type form for sign up
2. [x] Create page for sign up form
3. [x] Linked from main navigation 
3. [x] Embed type form on new page
