### ISSUE TITLE
Slack - Invite limit reached

### ISSUE THREAD

**Issue by charlottebrf** [HackBrexit/hackbrexit.github.io#24]
![screen shot 2016-09-08 at 17 51 02](https://cloud.githubusercontent.com/assets/16884984/18358440/f87b6bf8-75ec-11e6-8e13-a90010c92703.png)

**Comment by eddiejaoude** [comment]
> Slack may limit a team's ability to send more invitations if a large number has been sent but very few have been accepted.
> 
> If you're using Slack within a company setting and have reached a limit when inviting a large group of coworkers, please contact us.
> 
> If you're using Slack outside a company setting, you can avoid hitting the limit by only sending invitations to people who have asked to join your team. 
> 
> Please do not revoke invitations in an attempt to lift the limit. Invitation limits are not affected by revoked invitations. They are based solely on the acceptance rate of invitations that have already been sent.

Found this https://get.slack.help/hc/en-us/articles/201330256#invitation_limits

Two things we can do:
- Remove `pending` invites
- Contact **Slack**

**Comment by charlottebrf** [comment]
Thanks Eddie...I am inviting people manually who attended last session & emailing slack. Speak soon

**Comment by petered** [comment]
Well this is annoying.  I am trying to revive an old (non-company) slack workspace that exceeded its invite limit.  

Am I correct that the only way I can invite people is just to throw it away and start a new worldspace?
