### ISSUE TITLE
twitter feed for #hackbrexit

### ISSUE THREAD

**Issue by lubes72** [HackBrexit/hackbrexit.github.io#8]
suggestion for this feature

**Comment by charlottebrf** [comment]
Add Twitter hashtag widget to site: https://dev.twitter.com/web/embedded-timelines/search

**Comment by charlottebrf** [comment]
![screen shot 2016-11-18 at 13 13 26](https://cloud.githubusercontent.com/assets/16884984/20431206/d1ff657a-ad90-11e6-92e5-1ca31f2035c8.png)

Twitter widget now added.
